// <auto-generated />
using BSdigital_1.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BSdigital_1.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("BSdigital_1.Server.OrderBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("timestamp");

                    b.HasKey("Id");

                    b.ToTable("OrderBooks");
                });

            modelBuilder.Entity("BSdigital_1.Server.OrderBookEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("amount");

                    b.Property<int?>("OrderBookId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderBookId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("price");

                    b.HasKey("Id");

                    b.HasIndex("OrderBookId");

                    b.HasIndex("OrderBookId1");

                    b.ToTable("OrderBookEntry");

                    b.HasAnnotation("Relational:JsonPropertyName", "bids");
                });

            modelBuilder.Entity("BSdigital_1.Server.OrderBookEntry", b =>
                {
                    b.HasOne("BSdigital_1.Server.OrderBook", null)
                        .WithMany("Asks")
                        .HasForeignKey("OrderBookId");

                    b.HasOne("BSdigital_1.Server.OrderBook", null)
                        .WithMany("Bids")
                        .HasForeignKey("OrderBookId1");
                });

            modelBuilder.Entity("BSdigital_1.Server.OrderBook", b =>
                {
                    b.Navigation("Asks");

                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
